version: 2
jobs:

  lint:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/soundrop_otogibaraera

    steps:
      - run:
          name: Escape Japanese characters
          command: 'git config --global core.quotepath false'
      - checkout
      - restore_cache:
          keys:
            - v1-depedencies-{{ checksum "package.json" }}
            - v1-depedencies-
      - run:
          name: Install depends with npm
          command: npm install

      - save_cache:
          key: v1-depedencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"
    
      # Start Running ESLint
      - run:
          name: Running ESLint at src/
          command: |
            mkdir -p /tmp/eslint-reports/src_dir
            node_modules/.bin/eslint src/ --format junit --output-file /tmp/eslint-reports/src_dir/results.xml

      - store_test_results:
          path: /tmp/eslint-reports/src_dir
        
      - run:
          name: Running ESLint at src/Components/
          command: |
            mkdir -p /tmp/eslint-reports/components_dir
            node_modules/.bin/eslint src/Components/* --format junit --output-file /tmp/eslint-reports/components_dir/results.xml

      - store_test_results:
          path: /tmp/eslint-reports/components_dir

      - persist_to_workspace:
          root: .
          paths:
            - ./


  build:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/soundrop_otogibaraera

    steps:
      - attach_workspace:
          at: .
  
      - run: 
          name: building
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - ./
  

  Deploy:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/soundrop_otogibaraera

    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys

      - run:  
          name: Start ssh-keyscan  
          command: |  
            ssh-keyscan -p ${SSH_PORT} ${HOST_NAME} >> ~/.ssh/known_hosts 
            
      - run:
          name: remove old files
          command: ssh -p ${SSH_PORT} ${USER_NAME}@${HOST_NAME} 'rm -rf ${PROJECT_DIRECTORY}'

      - run: 
          name: Deploy to EC2 docker-compose Server
          command: "scp -r -P ${SSH_PORT} build  ${USER_NAME}@${HOST_NAME}:${PROJECT_DIRECTORY}"

workflows:
  version: 2
  Lintcheck_And_Build:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - Deploy:
          requires:
            - build
          filters:
            branches:
              only: master