version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/soundrop_otogibaraera

    steps:
      - run:
          name: Escape Japanese characters
          command: 'git config --global core.quotepath false'
      - checkout
      - restore_cache:
          keys:
            - v1-depedencies-{{ checksum "package.json" }}
            - v1-depedencies-
      - run:
          name: Install depends with npm
          command: npm install

      - save_cache:
          key: v1-depedencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      
      - run: 
          name: building
          command: npm run build

      - add_ssh_keys

      - run:  
          name: Start ssh-keyscan  
          command: |  
            ssh-keyscan -p ${SSH_PORT} ${HOST_NAME} >> ~/.ssh/known_hosts  
      - run: 
          name: Deploy to EC2 docker-compose Server
          command: ssh -p ${SSH_PORT} ${USER_NAME}@${HOST_NAME} 'cd soundrop_OtogibaraEra && git pull && npm i && npm run build && rm -rf ~/refine_huequica.xyz/works/content/soundrop_otogibara && mv build ~/refine_huequica.xyz/works/content/soundrop_otogibara'
workflows:
  version: 2
  Build and Test:
    jobs:
      - build